### ISSUE TITLE
add README

### ISSUE THREAD

**Issue by SanketDG** [ShearOfDoom/CactusReborn#2]
A informative README is required for the project, to state what the library does and useful links to installation, documentation and tutorials, etc.

**Comment by Ethan-Bierlein** [comment]
There's a `/Info` folder in the top project directory. In there is a `readme.md` file. https://github.com/ShearOfDoom/CactusReborn/blob/master/Info/readme.md

**Comment by SanketDG** [comment]
Uh, yes, but it should be in the ROOT directory.

**Comment by Ethan-Bierlein** [comment]
I'm going to politely disagree. If anyone visits the repository on Github, they'll see a link to the readme at the top, and a helpfully labeled "Info" folder.

**Comment by SanketDG** [comment]
Every project should have a README. Just state one line about the project, and the link to the info/readme
