### ISSUE TITLE
add documentation

### ISSUE THREAD

**Issue by SanketDG** [ShearOfDoom/CactusReborn#3]
The wiki tutorial is great, but it wont be enough for people who want to get started and then dive deeper.
A dedicated documentation site would be great. For something with minimal setup, take a look at [mkdocs](http://www.mkdocs.org/)

**Comment by Ethan-Bierlein** [comment]
I agree. There might not be a documentation site at this point in the project, but at some point there should be a site up and running. Not yet though.
